POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email":"test@test.com",
    "password":"12345"
}

###
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email":"test@test.com",
    "password":"12345"
}

###
GET http://localhost:3000/auth/whoami

###
POST http://localhost:3000/auth/signout

### 
GET http://localhost:3000/auth/1

###
GET http://localhost:3000/auth?email=deep@gmail.com

###
DELETE http://localhost:3000/auth/5

###
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "email":"deep3@gmail.com"
}